/* eslint-disable sonarjs/no-hardcoded-passwords */
import { QueryInterface } from 'sequelize';

import { AccountTypeEnum } from '../../enums/index.enum.ts';

export default {
    async up(queryInterface: QueryInterface) {
        await queryInterface.bulkInsert('accounts', [
            {
                username: 'tbettison0',
                email: 'tbettison0@cbc.ca',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Tanya',
                lastName: 'Bettison',
                accountType: AccountTypeEnum.CHIRPER,
            },
            {
                username: 'jdefreyne1',
                email: 'jdefreyne1@wisc.edu',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Jillian',
                lastName: 'De Freyne',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'cbalchin2',
                email: 'cbalchin2@washingtonpost.com',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Curran',
                lastName: 'Balchin',
                accountType: AccountTypeEnum.CHIRPER,
            },
            {
                username: 'mstandeven3',
                email: 'mstandeven3@vistaprint.com',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Mylo',
                lastName: 'Standeven',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'dlawrence4',
                email: 'dlawrence4@bigcartel.com',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Darill',
                lastName: 'Lawrence',
                accountType: AccountTypeEnum.CHIRPER,
            },
            {
                username: 'binskipp5',
                email: 'binskipp5@printfriendly.com',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Bambie',
                lastName: 'Inskipp',
                profileImageUrl: 'https://dummyimage.com/236x243.png/cc0000/ffffff',
                accountType: AccountTypeEnum.CHIRPER,
            },
            {
                username: 'fwelch6',
                email: 'fwelch6@spotify.com',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Foss',
                lastName: 'Welch',
                profileImageUrl: 'https://dummyimage.com/109x161.png/5fa2dd/ffffff',
                accountType: AccountTypeEnum.CHIRPER,
            },
            {
                username: 'aalwen7',
                email: 'aalwen7@simplemachines.org',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Ann',
                lastName: 'Alwen',
                profileImageUrl: 'https://dummyimage.com/244x176.png/cc0000/ffffff',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'bscoterbosh8',
                email: 'bscoterbosh8@bloomberg.com',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Barnard',
                lastName: 'Scoterbosh',
                profileImageUrl: 'https://dummyimage.com/106x219.png/5fa2dd/ffffff',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'amccard9',
                email: 'amccard9@goo.ne.jp',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Ambrosio',
                lastName: 'McCard',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'pcranmera',
                email: 'pcranmera@irs.gov',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Pietra',
                lastName: 'Cranmer',
                profileImageUrl: 'https://dummyimage.com/172x203.png/ff4444/ffffff',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'edunfordb',
                email: 'edunfordb@youku.com',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Eddie',
                lastName: 'Dunford',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'ikilligrewc',
                email: 'ikilligrewc@studiopress.com',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Ingrim',
                lastName: 'Killigrew',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'eplaitd',
                email: 'eplaitd@nydailynews.com',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Emile',
                lastName: 'Plait',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'inutbeame',
                email: 'inutbeame@msn.com',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Isidora',
                lastName: 'Nutbeam',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'eastletf',
                email: 'eastletf@youtube.com',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Ellary',
                lastName: 'Astlet',
                profileImageUrl: 'https://dummyimage.com/115x146.png/5fa2dd/ffffff',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'cfortescueg',
                email: 'cfortescueg@boston.com',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Crissy',
                lastName: 'Fortescue',
                profileImageUrl: 'https://dummyimage.com/249x167.png/5fa2dd/ffffff',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'hshawcrossh',
                email: 'hshawcrossh@ning.com',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Harold',
                lastName: 'Shawcross',
                profileImageUrl: 'https://dummyimage.com/241x184.png/5fa2dd/ffffff',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'cfiggeni',
                email: 'cfiggeni@goo.gl',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Corella',
                lastName: 'Figgen',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'rciccottioj',
                email: 'rciccottioj@mail.ru',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Rosabel',
                lastName: 'Ciccottio',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'ndomnickk',
                email: 'ndomnickk@whitehouse.gov',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Nerte',
                lastName: 'Domnick',
                profileImageUrl: 'https://dummyimage.com/162x247.png/cc0000/ffffff',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'egendrickel',
                email: 'egendrickel@constantcontact.com',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Etan',
                lastName: 'Gendricke',
                profileImageUrl: 'https://dummyimage.com/186x133.png/dddddd/000000',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'asizelandm',
                email: 'asizelandm@alibaba.com',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Andi',
                lastName: 'Sizeland',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'rgoldwatern',
                email: 'rgoldwatern@tripadvisor.com',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Ransell',
                lastName: 'Goldwater',
                profileImageUrl: 'https://dummyimage.com/155x188.png/ff4444/ffffff',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'ctregaleo',
                email: 'ctregaleo@google.co.uk',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Cherry',
                lastName: 'Tregale',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'ibohanp',
                email: 'ibohanp@ft.com',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Ilaire',
                lastName: 'Bohan',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'dcordeauq',
                email: 'dcordeauq@t-online.de',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Darla',
                lastName: 'Cordeau]',
                profileImageUrl: 'https://dummyimage.com/106x112.png/ff4444/ffffff',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'tkaasr',
                email: 'tkaasr@ameblo.jp',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Theresa',
                lastName: 'Kaas',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'gedworthyes',
                email: 'gedworthyes@usatoday.com',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Gardy',
                lastName: 'Edworthye',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'rnoltet',
                email: 'rnoltet@usnews.com',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Rivalee',
                lastName: 'Nolte',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'ggamilu',
                email: 'ggamilu@ft.com',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Giana',
                lastName: 'Gamil',
                profileImageUrl: 'https://dummyimage.com/108x186.png/ff4444/ffffff',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'kthomasv',
                email: 'kthomasv@soundcloud.com',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Kathy',
                lastName: 'Thomas',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'hkrystofw',
                email: 'hkrystofw@zdnet.com',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Hilde',
                lastName: 'Krystof',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'jbardwellx',
                email: 'jbardwellx@illinois.edu',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Jere',
                lastName: 'Bardwell',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'mgippsy',
                email: 'mgippsy@jimdo.com',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Marchall',
                lastName: 'Gipps',
                profileImageUrl: 'https://dummyimage.com/147x164.png/5fa2dd/ffffff',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'cpeltzz',
                email: 'cpeltzz@skype.com',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Cyndy',
                lastName: 'Peltz',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'hgoozee10',
                email: 'hgoozee10@phpbb.com',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Hermine',
                lastName: 'Goozee',
                profileImageUrl: 'https://dummyimage.com/197x239.png/ff4444/ffffff',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'teady11',
                email: 'teady11@pagesperso-orange.fr',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Tanney',
                lastName: 'Eady',
                profileImageUrl: 'https://dummyimage.com/233x231.png/cc0000/ffffff',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'ghumbey12',
                email: 'ghumbey12@dell.com',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Glen',
                lastName: 'Humbey',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'ioreagan13',
                email: 'ioreagan13@kickstarter.com',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Imogene',
                lastName: "O'Reagan",
                profileImageUrl: 'https://dummyimage.com/222x229.png/ff4444/ffffff',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'efardell14',
                email: 'efardell14@vimeo.com',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Evaleen',
                lastName: 'Fardell',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'escougal15',
                email: 'escougal15@rediff.com',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Eveline',
                lastName: 'Scougal',
                profileImageUrl: 'https://dummyimage.com/228x208.png/ff4444/ffffff',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'lkenen16',
                email: 'lkenen16@jimdo.com',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Lorrie',
                lastName: 'Kenen',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'cdinesen17',
                email: 'cdinesen17@jugem.jp',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Carin',
                lastName: 'Dinesen',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'pleyre18',
                email: 'pleyre18@wufoo.com',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Patsy',
                lastName: 'Leyre',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'fclapperton19',
                email: 'fclapperton19@cbsnews.com',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Freddie',
                lastName: 'Clapperton',
                profileImageUrl: 'https://dummyimage.com/143x157.png/dddddd/000000',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'mcolwell1a',
                email: 'mcolwell1a@walmart.com',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Moises',
                lastName: 'Colwell',
                profileImageUrl: 'https://dummyimage.com/237x237.png/cc0000/ffffff',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'crichen1b',
                email: 'crichen1b@businessweek.com',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Christophorus',
                lastName: 'Richen',
                profileImageUrl: 'https://dummyimage.com/212x220.png/cc0000/ffffff',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'alowthian1c',
                email: 'alowthian1c@nyu.edu',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Anabel',
                lastName: 'Lowthian',
                profileImageUrl: 'https://dummyimage.com/222x109.png/5fa2dd/ffffff',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'jquelch1d',
                email: 'jquelch1d@state.tx.us',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Jabez',
                lastName: 'Quelch',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'mrojas1e',
                email: 'mrojas1e@hubpages.com',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Mayor',
                lastName: 'Rojas',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'mthorrold1f',
                email: 'mthorrold1f@pagesperso-orange.fr',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Margarita',
                lastName: 'Thorrold',
                profileImageUrl: 'https://dummyimage.com/233x202.png/cc0000/ffffff',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'cradnedge1g',
                email: 'cradnedge1g@nbcnews.com',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Cosimo',
                lastName: 'Radnedge',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'amagor1h',
                email: 'amagor1h@mediafire.com',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Abelard',
                lastName: 'Magor',
                profileImageUrl: 'https://dummyimage.com/178x236.png/cc0000/ffffff',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'bberthe1i',
                email: 'bberthe1i@usgs.gov',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Benyamin',
                lastName: 'Berthe',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'kmurname1j',
                email: 'kmurname1j@ask.com',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Karissa',
                lastName: 'Murname',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'aliggins1k',
                email: 'aliggins1k@soundcloud.com',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Abeu',
                lastName: 'Liggins',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'jpigne1l',
                email: 'jpigne1l@businessweek.com',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Jordon',
                lastName: 'Pigne',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'tboram1m',
                email: 'tboram1m@cam.ac.uk',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Tobye',
                lastName: 'Boram',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'kgurys1n',
                email: 'kgurys1n@yahoo.co.jp',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Karie',
                lastName: 'Gurys',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'apurchon1o',
                email: 'apurchon1o@furl.net',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Asia',
                lastName: 'Purchon',
                profileImageUrl: 'https://dummyimage.com/236x105.png/dddddd/000000',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'dranns1p',
                email: 'dranns1p@bravesites.com',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Dewitt',
                lastName: 'Ranns',
                profileImageUrl: 'https://dummyimage.com/109x203.png/cc0000/ffffff',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'ffeeham1q',
                email: 'ffeeham1q@indiegogo.com',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Fidel',
                lastName: 'Feeham',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'sbarock1r',
                email: 'sbarock1r@cam.ac.uk',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Sal',
                lastName: 'Barock',
                profileImageUrl: 'https://dummyimage.com/171x131.png/dddddd/000000',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'rwyldbore1s',
                email: 'rwyldbore1s@cocolog-nifty.com',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Ruy',
                lastName: 'Wyldbore',
                profileImageUrl: 'https://dummyimage.com/137x104.png/ff4444/ffffff',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'jkydde1t',
                email: 'jkydde1t@cdbaby.com',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Jaime',
                lastName: 'Kydde',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'jciciura1u',
                email: 'jciciura1u@google.de',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Jabez',
                lastName: 'Ciciura',
                profileImageUrl: 'https://dummyimage.com/187x191.png/ff4444/ffffff',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'borridge1v',
                email: 'borridge1v@opensource.org',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Brandais',
                lastName: 'Orridge',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'hdurant1w',
                email: 'hdurant1w@merriam-webster.com',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Holden',
                lastName: 'Durant',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'rolesen1x',
                email: 'rolesen1x@ustream.tv',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Raina',
                lastName: 'Olesen',
                profileImageUrl: 'https://dummyimage.com/142x125.png/dddddd/000000',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'agallifont1y',
                email: 'agallifont1y@yellowbook.com',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Arlyn',
                lastName: 'Gallifont',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'jdeantoni1z',
                email: 'jdeantoni1z@rambler.ru',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Jourdan',
                lastName: 'De Antoni',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'dhenden20',
                email: 'dhenden20@prweb.com',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Dante',
                lastName: 'Henden',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'cpallaske21',
                email: 'cpallaske21@pinterest.com',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Chery',
                lastName: 'Pallaske',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'rflipsen22',
                email: 'rflipsen22@blogs.com',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Ronica',
                lastName: 'Flipsen',
                profileImageUrl: 'https://dummyimage.com/230x207.png/5fa2dd/ffffff',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'jutting23',
                email: 'jutting23@blinklist.com',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Jessie',
                lastName: 'Utting',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'vciraldo24',
                email: 'vciraldo24@senate.gov',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Vassily',
                lastName: 'Ciraldo',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'dmeconi25',
                email: 'dmeconi25@state.gov',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Danie',
                lastName: 'Meconi',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'wtowler26',
                email: 'wtowler26@merriam-webster.com',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Witty',
                lastName: 'Towler',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'gbulman27',
                email: 'gbulman27@bandcamp.com',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Granthem',
                lastName: 'Bulman',
                profileImageUrl: 'https://dummyimage.com/136x130.png/ff4444/ffffff',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'nprettyjohn28',
                email: 'nprettyjohn28@microsoft.com',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Nealon',
                lastName: 'Prettyjohn',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'phethron29',
                email: 'phethron29@amazon.com',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Peyton',
                lastName: 'Hethron',
                profileImageUrl: 'https://dummyimage.com/154x127.png/ff4444/ffffff',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'agartin2a',
                email: 'agartin2a@cbsnews.com',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Annora',
                lastName: 'Gartin',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'ekinman2b',
                email: 'ekinman2b@newyorker.com',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Elvin',
                lastName: 'Kinman',
                profileImageUrl: 'https://dummyimage.com/237x164.png/5fa2dd/ffffff',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'mgannicott2c',
                email: 'mgannicott2c@surveymonkey.com',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Mommy',
                lastName: 'Gannicott',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'cwestlake2d',
                email: 'cwestlake2d@google.com.br',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Charleen',
                lastName: 'Westlake',
                profileImageUrl: 'https://dummyimage.com/248x163.png/5fa2dd/ffffff',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'cmcilrath2e',
                email: 'cmcilrath2e@icq.com',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Caryl',
                lastName: 'McIlrath',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'jharrowsmith2f',
                email: 'jharrowsmith2f@live.com',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Jewelle',
                lastName: 'Harrowsmith',
                profileImageUrl: 'https://dummyimage.com/115x101.png/5fa2dd/ffffff',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'daspinell2g',
                email: 'daspinell2g@domainmarket.com',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Dale',
                lastName: 'Aspinell',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'mcharrier2h',
                email: 'mcharrier2h@craigslist.org',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Mortie',
                lastName: 'Charrier',
                profileImageUrl: 'https://dummyimage.com/173x235.png/5fa2dd/ffffff',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'fmoxon2i',
                email: 'fmoxon2i@microsoft.com',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Fulton',
                lastName: 'Moxon',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'cdeacock2j',
                email: 'cdeacock2j@ehow.com',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Cassie',
                lastName: 'Deacock',
                profileImageUrl: 'https://dummyimage.com/184x162.png/ff4444/ffffff',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'cmarin2k',
                email: 'cmarin2k@booking.com',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Clint',
                lastName: 'Marin',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'ietchell2l',
                email: 'ietchell2l@list-manage.com',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Ibrahim',
                lastName: 'Etchell',
                profileImageUrl: 'https://dummyimage.com/150x179.png/cc0000/ffffff',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'qbernet2m',
                email: 'qbernet2m@google.co.jp',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Quint',
                lastName: 'Bernet',
                profileImageUrl: 'https://dummyimage.com/210x168.png/5fa2dd/ffffff',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'kyeowell2n',
                email: 'kyeowell2n@japanpost.jp',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Kimberlee',
                lastName: 'Yeowell',
                profileImageUrl: 'https://dummyimage.com/220x116.png/5fa2dd/ffffff',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'rplesing2o',
                email: 'rplesing2o@hibu.com',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Rebeca',
                lastName: 'Plesing',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'ptewkesberry2p',
                email: 'ptewkesberry2p@youtube.com',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Pacorro',
                lastName: 'Tewkesberry',
                profileImageUrl: 'https://dummyimage.com/124x225.png/cc0000/ffffff',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'lspottswood2q',
                email: 'lspottswood2q@spotify.com',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Layne',
                lastName: 'Spottswood',
                accountType: AccountTypeEnum.TWIPPER,
            },
            {
                username: 'dmaccaughey2r',
                email: 'dmaccaughey2r@soup.io',
                password: '$2b$12$d3BF1CWxt44nuXwL55Hxg.soiUBffTdEwcyD.Anp07.kudHkJmtLK',
                firstName: 'Delcina',
                lastName: 'MacCaughey',
                profileImageUrl: 'https://dummyimage.com/116x243.png/dddddd/000000',
                accountType: AccountTypeEnum.TWIPPER,
            },
        ]);
    },
    async down(queryInterface: QueryInterface) {
        await queryInterface.bulkDelete('accounts', {});
    },
};
