/* eslint-disable sonarjs/class-name */
import type * as Model from './index.core.openwebui.model.ts';

export interface open_webui__routers__retrieval__ConfigForm {
    RAG_TEMPLATE?: string | null;
    TOP_K?: number | null;
    BYPASS_EMBEDDING_AND_RETRIEVAL?: boolean | null;
    RAG_FULL_CONTEXT?: boolean | null;
    ENABLE_RAG_HYBRID_SEARCH?: boolean | null;
    TOP_K_RERANKER?: number | null;
    RELEVANCE_THRESHOLD?: number | null;
    HYBRID_BM25_WEIGHT?: number | null;
    CONTENT_EXTRACTION_ENGINE?: string | null;
    PDF_EXTRACT_IMAGES?: boolean | null;
    DATALAB_MARKER_API_KEY?: string | null;
    DATALAB_MARKER_API_BASE_URL?: string | null;
    DATALAB_MARKER_ADDITIONAL_CONFIG?: string | null;
    DATALAB_MARKER_SKIP_CACHE?: boolean | null;
    DATALAB_MARKER_FORCE_OCR?: boolean | null;
    DATALAB_MARKER_PAGINATE?: boolean | null;
    DATALAB_MARKER_STRIP_EXISTING_OCR?: boolean | null;
    DATALAB_MARKER_DISABLE_IMAGE_EXTRACTION?: boolean | null;
    DATALAB_MARKER_FORMAT_LINES?: boolean | null;
    DATALAB_MARKER_USE_LLM?: boolean | null;
    DATALAB_MARKER_OUTPUT_FORMAT?: string | null;
    EXTERNAL_DOCUMENT_LOADER_URL?: string | null;
    EXTERNAL_DOCUMENT_LOADER_API_KEY?: string | null;
    TIKA_SERVER_URL?: string | null;
    DOCLING_SERVER_URL?: string | null;
    DOCLING_PARAMS?: Record<string, unknown> | null;
    DOCLING_DO_OCR?: boolean | null;
    DOCLING_FORCE_OCR?: boolean | null;
    DOCLING_OCR_ENGINE?: string | null;
    DOCLING_OCR_LANG?: string | null;
    DOCLING_PDF_BACKEND?: string | null;
    DOCLING_TABLE_MODE?: string | null;
    DOCLING_PIPELINE?: string | null;
    DOCLING_DO_PICTURE_DESCRIPTION?: boolean | null;
    DOCLING_PICTURE_DESCRIPTION_MODE?: string | null;
    DOCLING_PICTURE_DESCRIPTION_LOCAL?: Record<string, unknown> | null;
    DOCLING_PICTURE_DESCRIPTION_API?: Record<string, unknown> | null;
    DOCUMENT_INTELLIGENCE_ENDPOINT?: string | null;
    DOCUMENT_INTELLIGENCE_KEY?: string | null;
    MISTRAL_OCR_API_KEY?: string | null;
    MINERU_API_MODE?: string | null;
    MINERU_API_URL?: string | null;
    MINERU_API_KEY?: string | null;
    MINERU_PARAMS?: Record<string, unknown> | null;
    RAG_RERANKING_MODEL?: string | null;
    RAG_RERANKING_ENGINE?: string | null;
    RAG_EXTERNAL_RERANKER_URL?: string | null;
    RAG_EXTERNAL_RERANKER_API_KEY?: string | null;
    TEXT_SPLITTER?: string | null;
    CHUNK_SIZE?: number | null;
    CHUNK_OVERLAP?: number | null;
    FILE_MAX_SIZE?: number | null;
    FILE_MAX_COUNT?: number | null;
    FILE_IMAGE_COMPRESSION_WIDTH?: number | null;
    FILE_IMAGE_COMPRESSION_HEIGHT?: number | null;
    ALLOWED_FILE_EXTENSIONS?: string[] | null;
    ENABLE_GOOGLE_DRIVE_INTEGRATION?: boolean | null;
    ENABLE_ONEDRIVE_INTEGRATION?: boolean | null;
    web?: Model.WebConfig | null;
}
