export interface TaskConfigForm {
    TASK_MODEL: string | null;
    TASK_MODEL_EXTERNAL: string | null;
    ENABLE_TITLE_GENERATION: boolean;
    TITLE_GENERATION_PROMPT_TEMPLATE: string;
    IMAGE_PROMPT_GENERATION_PROMPT_TEMPLATE: string;
    ENABLE_AUTOCOMPLETE_GENERATION: boolean;
    AUTOCOMPLETE_GENERATION_INPUT_MAX_LENGTH: number;
    TAGS_GENERATION_PROMPT_TEMPLATE: string;
    FOLLOW_UP_GENERATION_PROMPT_TEMPLATE: string;
    ENABLE_FOLLOW_UP_GENERATION: boolean;
    ENABLE_TAGS_GENERATION: boolean;
    ENABLE_SEARCH_QUERY_GENERATION: boolean;
    ENABLE_RETRIEVAL_QUERY_GENERATION: boolean;
    QUERY_GENERATION_PROMPT_TEMPLATE: string;
    TOOLS_FUNCTION_CALLING_PROMPT_TEMPLATE: string;
}
